[package]
name = "os"
version = "0.1.0"
author = "egg"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
core-panic = []
format-args-nl = []
panic-info-message = []